plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: '@yarnpkg/plugin-stage'

yarnPath: .yarn/releases/yarn-2.1.1.cjs

packageExtensions:
  # jest-environment-puppeteer@*:
  #   peerDependencies:
  #     puppeteer: '*'
  #     jest-environment-node: '*'
  # jest-puppeteer@*:
  #   dependencies:
  # jest-environment-node: '*'
  'jest-environment-puppeteer@*':
    peerDependencies:
      puppeteer: '*'
    dependencies:
      jest-environment-node: '*'
